server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secuirty
    username: springstudent
    password: springstudent
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
